export default {
    'Terms of Service': `Updated October 9, 2022 

    These terms of use are entered into by and between You (“user,” “you,” and/or “your”) and RolldUp Inc. (“RolldUp,” “Company,” “we,” “our," and/or “us“). The following terms and conditions, together with any documents they expressly incorporate by reference collectively, (“Terms of Use“), govern your access to and use of the RolldUp mobile device software application (the “Mobile Application”), the website RolldUp www.rolldupapp.com (the “Website“), and any other mobile or web services, content, functionality, and services offered or applications owned, controlled, or offered by RolldUp (collectively, the “Services”), whether as a guest or a registered user. Please read the Terms of Use carefully before you start to use the Services. If you do not want to agree to these Terms of Use or the Privacy Policy (“Privacy Policy”), you must not access or use the Services. By using the Services, you represent and warrant that you meet all of the foregoing eligibility requirements. If you do not meet all of these requirements, you must not access or use the Services.  
    
    Please note: these Terms govern disputes between us, and contains an arbitration clause and class action waiver that requires you and RolldUp to resolve all disputes with each other on an individual basis through final and binding arbitration. Please read these terms carefully.  
    
    Certain areas of the Services (and your access to or use therein) may have additional terms, conditions, policies, rules, and guidelines, which govern your access to and use of such Websites and Services (as applicable, the “Additional Terms”). The Additional Terms will be posted (via a link) on the applicable Services and may be modified from time to time. To the extent there is a conflict between these Terms and any Additional Terms for a specific Service, the applicable Additional Terms shall govern and take precedence over these Terms with respect to your use of or access to that Website or Service.  
    
    Please also review RolldUp’s Privacy Policy, which governs RolldUp’s collection and use of your personal information. Registration data and certain other information about you is subject to our Privacy Policy. You understand that through your access or use of any Services, you consent to the collection and use (as set forth in the Privacy Policy) of this information, including the transfer of information to the United States and/or other countries for storage, processing, and use by RolldUp.`,
    'Acknowledgements & Disclaimers': `THESE TERMS OF USE (“AGREEMENT”) SETS FORTH THE LEGALLY BINDING TERMS FOR YOUR USE OF THE SERVICES. BY ACCESSING OR USING THE SERVICES, YOU ARE ACCEPTING THIS AGREEMENT AND YOU REPRESENT AND WARRANT THAT YOU HAVE THE RIGHT, AUTHORITY, AND CAPACITY TO ENTER INTO THIS AGREEMENT. YOU MAY NOT ACCESS OR USE THE SERVICES OR ACCEPT THE AGREEMENT IF YOU DO NOT HAVE THE CAPACITY TO ENTER INTO THIS AGREEMENT. IF YOU DO NOT AGREE WITH ALL OF THE PROVISIONS OF THIS AGREEMENT, DO NOT ACCESS AND/OR USE THE SERVICES. IF YOU ARE USING THE SERVICES ON BEHALF OF A COMPANY, ENTITY, OR ORGANIZATION, YOU REPRESENT AND WARRANT THAT YOU ARE AN AUTHORIZED REPRESENTATIVE OF SUCH COMPANY, ENTITY, OR ORGANIZATION WITH THE AUTHORITY TO BIND IT TO THIS AGREEMENT.  
    PLEASE READ THESE TERMS CAREFULLY, AS THEY CONTAIN AN AGREEMENT TO ARBITRATE AND OTHER IMPORTANT INFORMATION REGARDING YOUR LEGAL RIGHTS, REMEDIES, AND OBLIGATIONS. THE AGREEMENT TO ARBITRATE REQUIRES (WITH LIMITED EXCEPTION) THAT YOU SUBMIT CLAIMS YOU HAVE AGAINST US TO BINDING AND FINAL ARBITRATION, AND FURTHER (1) YOU WILL ONLY BE PERMITTED TO PURSUE CLAIMS AGAINST COMPANY ON AN INDIVIDUAL BASIS, NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS OR REPRESENTATIVE ACTION OR PROCEEDING, AND (2) YOU WILL ONLY BE PERMITTED TO SEEK RELIEF (INCLUDING MONETARY, INJUNCTIVE, AND DECLARATORY RELIEF) ON AN INDIVIDUAL BASIS.  `,
    'IMPORTANT DISCLAIMERS': `ALL INFORMATION CONTAINED ON THE SERVICES IS FOR INFORMATIONAL PURPOSES ONLY. CONTENT POSTED BY ROLLDUP ON ANY WEBSITE, KIOSK, MOBILE APPLICATION, SOCIAL MEDIA CHANNEL, THIRD-PARTY CONTENT SERVICE, OR ADVERTISEMENT IS FOR INFORMATIONAL PURPOSES ONLY. ROLLDUP DOES NOT ENDORSE, AND IS NOT RESPONSIBLE FOR THE ACCURACY OR RELIABILITY OF, ANY OPINION, ADVICE, STATEMENT, OR OTHER INFORMATION MADE ON THE SERVICES, INCLUDING USER CONTENT AND THIRD-PARTY MATERIALS (EACH AS DEFINED BELOW). ROLLDUP IS NOT RESPONSIBLE FOR YOUR RELATIONSHIP WITH ANY DISPENSARY, RETAIL LOCATION, HEALTH CARE PROVIDER, ANY THIRD-PARTY, OR OTHER USERS OF THE SERVICES. ROLLDUP IS NOT OBLIGATED TO SCREEN DISPENSARIES, RETAIL LOCATIONS, HEALTH CARE PROVIDERS, OR THEIR MENUS, CONTENT, OR DEALS TO DETERMINE WHETHER THEY ARE QUALIFIED OR AUTHORIZED BY LAW TO PROVIDE THEIR SERVICES OR TO DETERMINE THE ACCURACY OF THEIR MENUS OR OTHER INFORMATION THEY PROVIDE.  
    ROLLDUP DOES NOT OFFER MEDICAL ADVICE. ANY INFORMATION ACCESSED THROUGH THE SERVICES, OR WITHIN ANY OF ROLLDUP’S SOCIAL MEDIA PAGES OR CHANNELS IS FOR INFORMATIONAL AND EDUCATIONAL PURPOSES ONLY, IS NOT INTENDED TO BE A SUBSTITUTE FOR MEDICAL ADVICE, DIAGNOSIS, OR TREATMENT, AND IS NOT INTENDED TO COVER ALL POSSIBLE USES, DIRECTIONS, PRECAUTIONS, OR ADVERSE EFFECTS. SUCH INFORMATION INCLUDES, WITHOUT LIMITATION, THIRD-PARTY MATERIALS, USER CONTENT, AND ROLLDUP-GENERATED CONTENT DERIVED FROM USER CONTENT (E.G., STRAIN HIGHLIGHTS, ATTRIBUTES, AND OTHER DATA). THE INFORMATION ON THE SERVICES AND PROVIDED VIA ROLLDUP’S SOCIAL MEDIA PAGES AND CHANNELS SHOULD NOT BE USED FOR THE DIAGNOSIS OR TREATMENT OF ANY MEDICAL CONDITION. ALWAYS CONSULT A QUALIFIED HEALTH CARE PROVIDER IF YOU HAVE ANY QUESTIONS ABOUT A MEDICAL CONDITION. NEVER DISREGARD PROFESSIONAL MEDICAL ADVICE OR DELAY IN SEEKING IT BECAUSE OF SOMETHING YOU HAVE READ ON THE SERVICES, OR ON ROLLDUP’S SOCIAL MEDIA PAGES AND CHANNELS  `,
    'Technology Platform Acknowledgment': `You expressly agree and acknowledge that RolldUp (i) is a technology platform; (ii) is not a cannabis retailer, cultivator, or brand; (iii) does not itself provide delivery of any cannabis or process payments for cannabis; and (iv) does not itself cultivate, manufacture, package, label, test, or sell cannabis. The third-party retailers and brands who list their cannabis-related or non-cannabis-related services or businesses on the Service (“Retailers”) are solely responsible for ensuring that their products or services are offered in a safe, legal, and compliant manner. RolldUp has no responsibility or liability for any products or services offered by any Retailer. Nor does RolldUp have any responsibility or liability for any reviews or statements posted on the Websites regarding any products or services offered by any Retailer. `,
    'ACKNOWLEDGEMENT OF FEDERAL LAW': `User expressly acknowledges that RolldUp is for residents of states and localities with laws regulating medical or the recreational use of cannabis only and that medical cannabis collectives and patients are established pursuant to their respective local laws. Marijuana is included on Schedule 1 under the United States Controlled Substances Act. Under the federal laws of the United States of America, manufacturing, distributing, dispensing or possession of marijuana is illegal, and individuals are subject to arrest and/or prosecution for doing so. User further acknowledges that medical use is not recognized as a valid defense under federal laws regarding marijuana. User also acknowledges that the interstate transportation of marijuana is a federal offense.  

    THE FOREGOING DISCLAIMERS AND LIMITATIONS ON LIABILITY SHALL NOT LIMIT THE MORE GENERAL DISCLAIMERS AND LIMITATIONS ON LIABILITY ELSEWHERE IN THIS AGREEMENT.  
    By using the Services or by clicking to accept or agree to the Terms of Use when this option is made available to you, you accept and agree to be bound and abide by these Terms of Use and our Privacy Policy, found at www.rolldupapp.com/policy/privacy-policy, incorporated herein by reference.`,
    'Acknowledgment of State Law': `You expressly acknowledge, understand, and agree that the use, possession, cultivation, manufacturing, transportation, and distribution of cannabis may be illegal in your state of residence and in the state you are located, unless all participants are acting completely within the scope of the state’s applicable laws.`,
    'Acknowledgment of the Laws of Your Location': `While the Services may be accessed from various locations, RolldUp only accepts listings from Retailers located in certain states, cities, counties, municipalities, provinces, and jurisdictions (“Service Area”). In all scenarios, you must abide by and follow the applicable laws of the state, city, county, municipality, province, or jurisdiction in which you are located in order to use the Services. You expressly acknowledge, understand, and agree to assume full responsibility for cooperating with the laws of your place of location while using the Services. RolldUp reserves the right to determine or change its Service Area in its sole discretion at any time.`,
    'Changes to the Terms of Use': `We may revise and update these Terms of Use from time to time in our sole discretion. All changes are effective immediately when we post them, and apply to all access to and use of the Services thereafter.  
    Your continued use of the Services following the posting of revised Terms of Use means that you accept and agree to the changes. You are expected to check this page from time to time so you are aware of any changes, as they are binding on you.`,
    'Accessing the Services and Account Security': '',
    'Eligibility': `You must be 21 years of age or a qualified medical marijuana patient to use the Services within the United States.  You may be asked to verify that you are over the applicable age limit during your use of the Services and you hereby agree that you shall not misrepresent your age. Without limiting the foregoing, the Services are not available to minors or suspended members or users. You further represent that any party you invite to participate in any of the Services is also of legal age as described above, and agree not to invite participation from anyone not of legal age as described above. 

    If you are using the Services on behalf of a business, you represent that you have the authority to bind the business to these Terms, the Additional Terms, the Privacy Policy, and any other related or pertinent agreements. The applicable business agrees to hold harmless and indemnify RolldUp and its affiliates, officers, agents, and employees from any claim, suit or action arising from or related to the use of the Services or violation of these terms, including any liability or expense arising from claims, losses, damages, suits, judgments, litigation costs, and attorneys’ fees. If you do not have such authority, you will be held individually liable for all actions taken under your user ID.`,
    'Account Creation': `In order to use certain feature of the Services, you must register for an account with RolldUp (“RolldUp Account”) and provide certain information about yourself as prompted by the Service registration form. You represent and warrant that: (a) all required registration information you submit is truthful and accurate; and (b) you will maintain the accuracy of such information at all times. You may not create more than one RolldUp Account. RolldUp may suspend or terminate your RolldUp Account in accordance with the provisions of this term of Use.`,
    'Account Deletion': `You may delete your RolldUp Account at any time, for any reason, by sending an email to asupport@rolldupapp.com which includes your RolldUp Account Username and your request to delete your account.`,
    'Account Responsibilities': `You are responsible for maintaining the confidentiality of your RolldUp Account login information and are fully responsible for all activities that occur under your RolldUp Account. You agree to immediately notify RolldUp of any unauthorized use, or suspected unauthorized use, of your RolldUp Account or any other breach of security. RolldUp cannot and will not be liable for any loss or damage arising from your failure to comply with the above requirements.`,
    'Social Networking Services': `Alternatively, we may permit you to login to the Services or otherwise associate your RolldUp Account with your login credentials from certain social networking sites (e.g., Facebook and Twitter) (“SNS”). If you log in or otherwise associate your RolldUp Account with your login credentials from a SNS, we may receive information about you from such SNS, in accordance with the terms and conditions (e.g., terms of use and privacy policy) of the SNS (“SNS Terms”). If you elect to share your information with these SNS, we will share information with them in accordance with your election. The SNS Terms of said SNS will apply to the information we disclose to them.`,
    'License': `Subject to the terms of this Agreement, RolldUp grants you a non-transferable, non-exclusive license to use the Services for your personal, noncommercial use. Subject to the terms of this Agreement, RolldUp grants you a non-transferable, non-exclusive license to install and use the Mobile Application, in executable object code format only, solely on your own handheld mobile device and for your personal, noncommercial use.`,
    'Certain Restrictions': `The rights granted to you in this Agreement are subject to the following restrictions: (a) you shall not license, sell, rent, lease, transfer, assign, distribute, host, or otherwise commercially exploit the Services; (b) you shall not modify, make derivative works of, disassemble, reverse compile or reverse engineer any part of the Services; (c) you shall not access the Services in order to build a similar or competitive service; and (d) except as expressly stated herein, no part of the Services may be copied, reproduced, distributed, republished, downloaded, displayed, posted or transmitted in any form or by any means. Any future release, update, or other addition to functionality of the Services shall be subject to the terms of this Agreement. All copyright and other proprietary notices on any of the Services’ content, and all on all copies thereof, must be retained.`,
    'Modification': `RolldUp reserves the right, at any time, to modify, suspend, or discontinue the Services or any part thereof with or without notice. You agree that RolldUp will not be liable to you or to any third party for any modification, suspension, or discontinuance of the Services or any part thereof.`,
    'Ownership': `Excluding User Content, you acknowledge that all the intellectual property rights in the Services are owned by RolldUp or RolldUp’s licensors. RolldUp’s provision of the Services under this Terms of Use does not transfer to you or any third party any rights, title, or interest in or any of the Service’s intellectual property rights. RolldUp and its suppliers reserve all rights not granted in this Agreement.`,
    'Mobile Application Platforms': `You acknowledge and agree that the availability of the Mobile Application is dependent on the third-party app platform from which you received the Mobile Application, e.g., the Apple App Store® or the Google Play® Store (“App Platform”). You acknowledge that this Agreement is between you and RolldUp and not with the App Platform. RolldUp, not the App Platform, is solely responsible for the Mobile Application, the content thereof, maintenance, support services, and warranty therefor, and addressing any claims relating thereto (e.g., product liability, legal compliance, or intellectual property infringement). You agree to pay all fees charged by the App Platform in connection with the Mobile Application. Each App Platform may have its own terms and conditions to which you must agree before downloading the Mobile Application from it. You agree to comply with, and your license to use the Mobile Application is conditioned upon your compliance with, all applicable agreements, terms, and conditions of use/service, and other policies of the applicable App Platform. You acknowledge that the App Platform (and its subsidiaries) is a third-party beneficiary of this Agreement and will have the right to enforce this Terms of Use. See Accessing and Downloading the Application from Apple® in below for additional terms and conditions if you access or download the Mobile Application from the Apple App Store.`,
    'Text Messaging': `By using the Services, you agree and consent to RolldUp and those acting on its behalf sending you text (SMS) messages at the phone number you provided us. These messages may include operational messages about your use of the Services, as well as marketing or other promotional messages. Messages from RolldUp, its affiliated companies and necessary third-party service providers, may include but are not limited to: operational communications concerning your User account or use of the Services, updates concerning new and existing features on RolldUp, communications concerning promotions run by us or our third-party partners, and news concerning RolldUp and industry developments. Standard text messaging charges applied by your cell phone carrier will apply to text messages we send. Your agreement to receive promotional texts is not a condition of purchase of any goods or services offered by RolldUp. If you change or deactivate the phone number you provided to RolldUp, you must update your account information to help prevent us from inadvertently communicating with anyone who acquires your old number. You agree that texts, calls, or prerecorded messages may be generated by automatic telephone dialing systems and hereby waive your right to pursue any claims arising under the Telephone Consumer Protection Act (“TCPA”). To the extent any claim under the TCPA is deemed un-waivable, you agree that by using the Services or accessing the Services, you are agreeing that any such un-waivable claim arising under the TCPA will be arbitrated on an individual, not class or representative, basis, as set forth in in this Terms of Use.`,
    'Opt-Out': `By signing this agreement, you are agreeing to receive text messages until you opt-out. You may opt out of receiving promotional text messages from RolldUp at any time by replying STOP to a promotional text message from RolldUp. You may opt-out of receiving all text messages from RolldUp at any time by deleting your account or by replying STOP to any text message from RolldUp. NOTE: if you opt-out of receiving all text messages from RolldUp, you will not be able to use certain Services without agreeing to receive operational text messages. You may continue to receive text messages for a short period while RolldUp processes your request, and you may also receive text messages confirming the receipt of your opt-out request. By signing this agreement, you are waiving your right to pursue any claims arising under the TCPA related to any messages sent to you while the opt-out request is pending. To the extent any claim under the TCPA is deemed un-waivable, you agree that by using the Services or accessing the Services, you are agreeing that any such un-waivable claim arising under the TCPA will be arbitrated on an individual, not class or representative, basis, as set forth in this Terms of Service.`,
    'Opting Back In': `You may opt back into receiving text messages from RolldUp at any time by replying START to a text message from RolldUp.`,
    'Push Notifications': `When you install our Mobile Application on your mobile device you agree to receive push notifications, which are messages an app sends you on your mobile device even when the Mobile App is not on. You can turn off notifications by visiting your mobile device’s “settings” page.`,
    'Email': `You agree that we may send you emails concerning our products and services, as well as those of third parties. You may opt-out of promotional emails by following the unsubscribe instructions in a promotional email.`,
    'User Content': `“User Content” means any and all information and content that a user submits to, or uses with, the Services, including without limitation, content in the user’s profile, user reviews and/or postings. You acknowledge and agree that RolldUp is not responsible for any User Content, including its accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality, or any other aspect thereof. RolldUp does not assume and will not have any liability or responsibility to you or any other person or user for your use or misuse of any User Content.`,
    'User Content – Restrictions': `You agree not to use the Services, or any of RolldUp’s social media pages or channels to collect, upload, transmit, display, or distribute any User Content that (a) violates any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; (b) is unlawful, harassing, abusive, tortious, threatening, harmful, invasive of another’s privacy, vulgar, defamatory, false, intentionally misleading, trade libelous, pornographic, obscene, patently offensive (e.g., material that promotes racism, bigotry, hatred, or physical harm of any kind against any group or individual) or otherwise objectionable material of any kind or nature; or (c) in violation of any law, regulation, or obligations or restrictions imposed by any third-party.`,
    'User Content – Your Responsibilities': `You are solely responsible for your User Content. You assume all risks associated with use of your User Content, including any reliance on its accuracy, completeness or usefulness by others, or any disclosure of your User Content that makes you or any third-party personally identifiable. You hereby represent and warrant that your User Content does not violate the Acceptable Use Policy outlined in this Terms of Service.  You may not state or imply that your User Content is in any way provided, sponsored, or endorsed by RolldUp. You acknowledge and agree that RolldUp is not responsible for any User Content, including its accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality, or any other aspect thereof. RolldUp does not assume and will not have any liability or responsibility to you or any other person or user for your use or misuse of any User Content. Because you alone are responsible for your User Content (and not RolldUp), you may expose yourself to liability if, for example, your User Content violates the Acceptable Use Policy or other applicable laws. RolldUp is not obligated to backup any User Content and User Content may be deleted at any time. You are solely responsible for creating backup copies of your User Content, if you desire.`,
    'Liscense': `You hereby grant, and you represent and warrant that you have the right to grant, to RolldUp an irrevocable, nonexclusive, royalty-free and fully-paid, worldwide license to reproduce, distribute, publicly display and perform, prepare derivative works of, incorporate into other works, and otherwise use your User Content, and to grant sublicenses of the foregoing, solely for the purposes of including your User Content in the Services. You agree to irrevocably waive (and cause to be waived) any claims and assertions of moral rights or attribution with respect to your User Content.`,
    'Feedback': `If you provide RolldUp any feedback or suggestions regarding the Services (“Feedback”), you hereby assign to RolldUp all rights in the Feedback and agree that RolldUp shall have the right to use such Feedback and related information in any manner it deems appropriate. RolldUp will treat any Feedback you provide to RolldUp as non-confidential and non-proprietary. You agree that you will not submit to RolldUp any information or ideas that you consider to be confidential or proprietary.`,
    'Reviews': `You must have a valid account and email address to leave a review on RolldUp. Prior to posting a review, you will need to verify your email address associated with your RolldUp account. You agree not to post reviews on the Service, or any of RolldUp’s social media pages or channels that are not based upon your personal experience or are otherwise designed for any purpose other than providing other users on the Services with an accurate description of your personal experience. Reviews based on secondhand, non-personal experience are not allowed. In addition to the other restrictions contained in the Acceptable Use Policy, reviews posted on the Services, or any of RolldUp’s social media pages or channels must not: (a) be written exclusively in capital letters; (b) be plagiarized; (c) contain spam, advertisements, and/or links to external websites; (d) contain disparaging information about any Dispensary employees or any other person, (e) contain overly detailed or sexual descriptions of an individual’s physical appearance, or lewd personal attacks against a specific individual or group of individuals affiliated with the Dispensary, (f) contain references to Dispensaries or competitors other than the product or Dispensary being reviewed, or (g) contain unrelated personal grievances. If you are an owner, volunteer, or employee of a Dispensary you may not post reviews about your Dispensary or products or about your competitors’ Dispensary or products. As an owner of a Dispensary, you are responsible for moderating and enforcing the Acceptable Use Policy on all reviews posted to your Dispensary page.`,
    'Photos': `Image files must exclusively feature the products they illustrate and must not include body parts, messy or cluttered backgrounds, product wrapping, currency, paraphernalia, brand names, or other any objects other than the product itself. Image files must be clear and must not be blurry, fuzzy, or contain any flash reflections. Products should be centered in the image file. Image files must contain an accurate depiction of the product they illustrate. Image files cannot contain pornography or other graphic images and must otherwise abide by the guidelines set forth in the Acceptable Use Policy in this Terms of Service.`,
    'Technological Restrictions': `In addition, you agree not to use the Services to: (a) upload, transmit, or distribute any computer viruses, worms, or any software intended to damage or alter a computer system or data; (b) send unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes, or any other form of duplicative or unsolicited messages, whether commercial or otherwise; (c) harvest, collect, gather or assemble information or data regarding other users, including e-mail addresses, without their consent; (d) interfere with, disrupt, or create an undue burden on servers or networks connected to the Services or violate the regulations, policies or procedures of such networks; (e) attempt to or impersonate another user or RolldUp or gain unauthorized access to the Service, other computer systems or networks connected to or used together with the Service, through password mining or other means; (f) harass or interfere with another user’s use and enjoyment of the Service; or (g) introduce software or automated agents or scripts to the Service so as to produce multiple accounts, generate automated searches, requests and queries, or to strip, scrape, or mine data from the Service.`,
    'Monitoring, Suspension, and Termination': `We reserve the right (but have no obligation) to review any User Content (including any image files or reviews), investigate, and/or take appropriate action against you in our sole discretion (including removing or the Terms Of Service, and/or reporting you to law enforcement authorities) if we in our sole discretion suspect that you have violated the Acceptable Use Policy or any other provision of this Agreement or otherwise create liability for us or any other person.`,
    'Indemnity': `You agree to indemnify and hold RolldUp (and its officers, employees, and agents) harmless from any and all losses, damages, liabilities, claims, actions, judgments, awards, penalties, fines, costs and/or expenses (including reasonably attorneys’ fees) arising from or relating to any claim or demand made by any third party due to or arising out of (i) your use or misuse of the Service, (ii) your User Content, (iii) your violation of this Agreement; or (iv) your violation of applicable laws or regulations. RolldUp reserves the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us and you agree to cooperate with our defense of these claims. You agree not to settle any matter without the prior written consent of RolldUp. RolldUp will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.`,
    'Third-Party Interactions': `During use of the Service, you may enter into correspondence with, purchase goods and/or services from, or participate in promotions of third-party service providers, advertisers, or sponsors showing their goods and/or services through the Service. In particular, RolldUp is not a party to any transaction that you may enter into with a third-party. Any such activity, and any terms, conditions, warranties, or representations associated with such activity, is solely between you and the applicable third-party. RolldUp shall have no liability, obligation or responsibility for any such correspondence, purchase, transaction, or promotion between you and any such third-party. You agree that it is your responsibility to take reasonable precautions in all actions and interactions with any third party you interact with through the Service.`,
    'Third-Party Materials': `The Services might display, include, or make available third-party content (including data, information, articles applications or other products, services and/or materials) or contain links to third party websites, services, and advertisements for third parties such as Deals and dispensary Menus, including pricing, product names, and product descriptions each Menu (defined below) (collectively, “Third-Party Materials”). You acknowledge and agree that RolldUp is not responsible for Third-Party Materials, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. RolldUp does not assume and will not have any liability or responsibility to you or any other person or user for any Third-Party Materials. Third-Party Materials and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk. When you link to a Third-Party Material, the applicable third party’s terms and policies apply, including the third party’s privacy and data gathering practices. You should make whatever investigation you feel necessary or appropriate before proceeding with any transaction in connection with such Third-Party Material.`,
    'Deals': `The Service might display, include, or make available coupons, promotional codes, giveaways, samples, and other offers from listed dispensaries (collectively, “Deals”). Deals constitute “Third Party Materials” under this Agreement. RolldUp displays these Deals on the Services as a form of advertisement for the listing dispensary (the “Offeror”) only. All Deals are offered directly by the applicable Offeror, and may be subject to additional terms, conditions, or restrictions of the Offeror or under applicable law, whether or not such additional terms, conditions, or restrictions are expressly included on the Services. The Offeror, and not RolldUp, is solely responsible for: (a) redemption of the Deal; (b) compliance of all aspects of the Deal with applicable law (including without limit, the advertisement, redemption, and terms, conditions and restrictions related thereto); (c) all goods and services it provides to you in connection with the Deal; and (d) all injuries, illnesses, damages, claims, liabilities and costs it may cause you to suffer, directly or indirectly, in full or in part, whether related to the use or redemption of a Deal or not.`,
    'Other Users': `Each user of the Services is solely responsible for any and all of its User Content and Third-Party Materials. Because we do not control User Content and/or Third-Party Materials, you acknowledge and agree that we are not responsible for any User Content and/or Third-Party Materials, we make no guarantees regarding the accuracy, currency, suitability, or quality of any User Content and/or Third-Party Materials, and we assume no responsibility for any User Content and/or Third-Party Materials. Your interactions with other Service users (including Dispensaries) are solely between you and such user. You agree that RolldUp will not be responsible for any loss or damage incurred as the result of any such interactions. If there is a dispute between you and any Service user, we are under no obligation to become involved.`,
    'Release': `In consideration of your use of the Services, you hereby release and forever discharge RolldUp (and our officers, employees, agents, successors, and assigns) from, and hereby waive and relinquish your rights with respect to, each and every past, present and future dispute, claim, controversy, demand, right, obligation, liability, action and cause of action of every kind and nature (including claims related to privacy, receipt of text messages, personal injuries, death, and property damage), known or unknown, that has arisen or arises directly or indirectly out of, or relates directly or indirectly to, any interactions with, or act or omission of, other Service users, IF YOU ARE A CALIFORNIA RESIDENT, YOU HEREBY WAIVE CALIFORNIA CIVIL CODE SECTION 1542 IN CONNECTION WITH THE FOREGOING, WHICH STATES: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR OR RELEASING PARTY DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE AND THAT, IF KNOWN BY HIM OR HER WOULD HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR OR RELEASED PARTY.” If you are a non-California resident, you hereby agree that the release above applies to all claims, including claims you did not know existed at the time you signed this Agreement.`,
    'Disclaimers': `THE SERVICES ARE PROVIDED “AS-IS” AND “AS AVAILABLE” AND WE (AND OUR SUPPLIERS) EXPRESSLY DISCLAIM, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, ANY WARRANTIES AND CONDITIONS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING THE WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, QUIET ENJOYMENT, ACCURACY, OR NON-INFRINGEMENT. WITHOUT LIMITING THE FOREGOING, ROLLDUP (AND OUR SUPPLIERS) MAKE NO WARRANTY THAT THE SERVICES: (A) WILL MEET YOUR REQUIREMENTS; (B) WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; OR (C) WILL BE ACCURATE, RELIABLE, FREE OF VIRUSES OR OTHER HARMFUL CODE, COMPLETE, LEGAL, OR SAFE.  
    SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU`,
    'Limitation on Liability': `TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL ROLLDUP (AND OUR SUPPLIERS) BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFIT OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES ARISING FROM OR RELATING TO THIS AGREEMENT OR YOUR USE OF, OR INABILITY TO USE, THE SERVICES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. ACCESS TO, AND USE OF, THE SERVICES ARE AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA RESULTING THEREFROM. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, ROLLDUP’S (AND OUR SUPPLIERS’) LIABILITY TO YOU FOR ANY DAMAGES ARISING FROM OR RELATED TO THIS AGREEMENT (FOR ANY CAUSE WHATSOEVER AND REGARDLESS OF THE FORM OF THE ACTION), WILL AT ALL TIMES BE LIMITED TO THE GREATER OF (A) FIFTY US DOLLARS ($50) OR (B) AMOUNTS YOU’VE PAID ROLLDUP IN THE PRIOR 12 MONTHS (IF ANY). THE EXISTENCE OF MORE THAN ONE CLAIM WILL NOT ENLARGE THIS LIMIT.  
    SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OF CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU AND YOU MAY ALSO HAVE OTHER LEGAL RIGHTS THAT VARY FROM JURISDICTION TO JURISDICTION.`,
    'Term and Termination': `Subject to this Section, this Terms of Service will remain in full force and effect while you use the Services. We may (a) suspend your rights to use the Services (including your RolldUp Account) or (b) terminate this Terms of Service at any time for any reason at our sole discretion, including for any use of the Services in violation of this Term of Service. Upon termination of this Terms of Service, your RolldUp Account and right to access and use the Services will terminate immediately. You understand that any termination of your RolldUp Account involves deletion of your User Content associated therewith from our Services, and live databases. RolldUp will not have any liability whatsoever to you for any termination of this Terms of Service, including for termination of your RolldUp Account or deletion of your User Content.`,
    'Copyright Policy': `RolldUp respects the intellectual property of others and asks that users of our Services do the same. In connection with our Services, we have adopted and implemented a policy respecting copyright law that provides for the removal of any infringing materials and for the termination, in appropriate circumstances, of users of our Services who are repeat infringers of intellectual property rights, including copyrights. If you believe that one of our users is, through the use of our Services, unlawfully infringing the copyright(s) in a work, and wish to have the allegedly infringing material removed, the following information in the form of a written notification (pursuant to 17 U.S.C. § 512(c)) must be provided the designated copyright agent for RolldUp:  

     - Your physical or electronic signature;  
    
     - Identification of the copyrighted work(s) that you claim to have been infringed;  
    
     - Identification of the material on our services that you claim is infringing and that you request us to remove;  
    
     - Sufficient information to permit us to locate such material;  
    
     - Your address, telephone number, and e-mail address;  
    
     - A statement that you have a good faith belief that use of the objectionable material is not authorized by the copyright owner, its agent, or under the law; and  
    
     - A statement that the information in the notification is accurate, and under penalty of perjury, that you are either the owner of the copyright that has allegedly been infringed or that you are authorized to act on behalf of the copyright owner.  
    
    Please note that, pursuant to 17 U.S.C. § 512(f), any misrepresentation of material fact (falsities) in a written notification automatically subjects the complaining party to liability for any damages, costs and attorney’s fees incurred by us in connection with the written notification and allegation of copyright infringement.  
    The Designated Copyright Agent for RolldUp is:  
     
    Copyright Agent, Legal Department  
    RolldUp Inc.  
    228 E Oklahoma St  
    Tulsa, Oklahoma 74106  
    Email: support@rolldupapp.com`,
    'Arbitration Agreement and Jury Trial Waiver, Class Action Waiver, and Forum Selection Clause': `Except for disputes brought in small claims court, all disputes between you and RolldUp arising out of, relating to or in connection with the Services shall be exclusively settled through binding arbitration pursuant to the then-current rules of the American Arbitration Association (“AAA”) for commercial arbitration and not in court. This agreement to arbitrate applies to any claim brought under the laws of any state or national government, including claims under the Telephone Consumer Protection Act of 1991, the Federal Trade Commission Act, the Consumer Product Safety Act, or any other federal, state or local law or ordinance. There is no judge or jury in arbitration and you are agreeing to waive your right to pursue claims in court to the greatest extent permitted by law. Arbitration procedures are simpler and more limited than rules applicable in court and review by a court is limited. YOU AND ROLLDUP AGREE THAT ANY SUCH ARBITRATION SHALL BE CONDUCTED ON AN INDIVIDUAL BASIS AND NOT IN A CLASS, CONSOLIDATED OR REPRESENTATIVE ACTION. Notwithstanding any provision in this Agreement to the contrary, if the class and representative-action waiver in the prior sentence is deemed invalid or unenforceable, however, neither you nor we are entitled to arbitration, and any class or representative-action claims shall proceed in a court of competent jurisdiction in Tulsa County, Oklahoma. This arbitration agreement is entered into and enforceable pursuant to the Federal Arbitration Act. The arbitrator’s award may be entered in any court of competent jurisdiction. Notwithstanding any provision in this Agreement to the contrary, we agree that if RolldUp makes any future change to this dispute resolution provision, it will not apply to any individual claim(s) about which you had already provided notice to RolldUp. Information on AAA and how to start arbitration can be found at www.adr.org or by calling 800-778-7879. If the arbitration in this Section provision is found unenforceable or to not apply for a given dispute, then the proceeding must be brought exclusively in a court of competent jurisdiction in Tulsa County, Oklahoma. You hereby accept the exclusive jurisdiction of such court for this purpose. To the extent enforceability of this Agreement requires reference to any state law, the Parties agree such reference shall be to the laws of the State of Oklahoma without regard to conflict of law provisions.  

    Pre-Arbitration Dispute Resolution. Prior to resorting to formal dispute resolution procedures, you hereby agree to try to resolve disputes amicably and efficiently by emailing customer support at support@rolldupapp.com. Any communication to us regarding any dispute you have must be sent within ninety calendar days of the date of the event giving rise to the dispute. You agree that engaging in this pre-arbitration dispute resolution procedure is a prerequisite to initiating a complaint in arbitration or any other form. If pre-arbitration dispute resolution efforts prove unsuccessful, a party who intends to seek arbitration must first send to the other, by certified mail, a written Notice of Dispute (“Notice”) within ninety calendar days of the date on which the parties agree that the pre-arbitration dispute resolution has failed. The Notice to us should be sent to the address identified below. You hereby agree that failure to follow any of the steps outlined in this paragraph operates as a waiver of your right to pursue your claims in arbitration or any other forum.  

    Confidentiality. All aspects of the arbitration proceeding, and any ruling, decision, or award by the arbitrator, will be strictly confidential for the benefit of all parties.  

    Future Changes to Arbitration Agreement. Notwithstanding any provision in these Terms to the contrary, we agree that if it makes any future change to this Arbitration Agreement (other than a change to the Notice Address) while you are a user of the Service, you may reject any such change by sending us written notice within thirty (30) calendar days of the change to the Notice Address provided in Section below. By rejecting any future change, you are agreeing that you will individually arbitrate any dispute between us in accordance with the language of this Arbitration Agreement as of the date you first accepted these Terms (or accepted any subsequent changes to these Terms).`,
    'General': ``,
    'No Support or Maintenance': `You acknowledge and agree that RolldUp will have no obligation to provide you with any support or maintenance in connection with the Services.`,
    'Changes to Terms of Use': `We may amend these Terms at any time in our sole discretion. If we do so, we will post the modified Terms on the Service. The modifications will be effective immediately. You agree to review these Terms periodically so that you are aware of any modifications. Continued use of our Services following notice of such changes shall indicate your acknowledgement of such changes and agreement to be bound by the terms and conditions of such changes.`,
    'Copyright/Trademark Information': `Copyright © 2023, RolldUp Inc. All rights reserved. RolldUp®; and the RolldUp Logo (collectively, the “Marks”) are trademarks of RolldUp Inc. Apple®, App Store®, and itunes® are reistered trademarks of Apple, Inc. (“Apple’). Google Play® is a trademark of Google, LLC. You acknowledge and agree that You are not permitted to use RolldUp’s Marks or any third-party marks displayed on our site without prior written consent from, respectively, RolldUp Inc., Apple, or the owners of such third-party marks.`,
    'Accessing and Downloading the Application from Apple': `The following additional terms apply to any Mobile App accessed through or downloaded from the iTunes® or the App Store® (“App Store Sourced Mobile App”):  
    You acknowledge and agree that (i) this Agreement is concluded between you and RolldUp only, and not Apple, and (ii) that RolldUp, not Apple, is solely responsible for the App Store Sourced Mobile Application content thereof. The license granted to you in the Agreement to use the App Store Sourced Mobile Application and Service is a non-transferable right to use the App Store Sourced Mobile Application on any Apple Device that you own or control, and only as permitted by the Usage Rules set forth in the App Store Terms of Service.  
    You acknowledge that Apple has no obligation whatsoever to furnish any maintenance and support services with respect to the App Store Sourced Mobile App.  
    In the event of any failure of the App Store Sourced Mobile Application to conform to any applicable warranty, you may notify Apple, and Apple will refund the purchase price for the App Store Sourced Mobile Application to you. To the maximum extent permitted by applicable law, Apple will have no other warranty obligation whatsoever with respect to the App Store Sourced Mobile App. As between RolldUp and Apple, any other claims, losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty will be the sole responsibility of RolldUp.  
    You and RolldUp acknowledge that, as between RolldUp and Apple, Apple is not responsible for addressing any claims you have or any claims of any third-party relating to the App Store Sourced Mobile Application or your possession and use of the App Store Sourced Mobile Application, including, but not limited to: (i) product liability claims; (ii) any claim that the App Store Sourced Mobile Application fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation.  
    You and RolldUp acknowledge that, in the event of any third-party claim that the App Store Sourced Mobile Application or your possession and use of that App Store Sourced Mobile Application infringes that third-party’s intellectual property rights, as between RolldUp and Apple, RolldUp, not Apple, will be solely responsible for the investigation, defense, settlement and discharge of any such intellectual property infringement claim to the extent required by the Terms.  
    You and RolldUp acknowledge and agree that Apple, and Apple’s subsidiaries, are third-party beneficiaries of the Agreement as related to your license of the App Store Sourced Mobile App, and that, upon your acceptance of the terms and conditions of the Agreement, Apple will have the right (and will be deemed to have accepted the right) to enforce the Agreement as related to your license of the App Store Sourced Mobile Application against you as a third-party beneficiary thereof.  
    You represent and warrant that (i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a “terrorist supporting” country; and (ii) you are not listed on any U.S. Government list of prohibited or restricted parties.  
    Without limiting any other terms of the Terms of Service, you must comply with all applicable third-party terms of agreement when using the App Store Sourced Mobile Application.`,
    'Miscellaneous': `This Agreement constitutes the entire agreement between you and us regarding the use of the Services. Our failure to exercise or enforce any right or provision of this Agreement shall not operate as a waiver of such right or provision, nor shall any single or partial exercise by RolldUp of any right or power hereunder preclude further exercise of that or any other right hereunder. The section titles in this Agreement are for convenience only and have no legal or contractual effect. The word “including” means “including without limitation.” If any provision of this Agreement is, for any reason, held to be invalid or unenforceable, the other provisions of this Agreement will be unimpaired and the invalid or unenforceable provision will be deemed modified so that it is valid and enforceable to the maximum extent permitted by law. Nothing contained herein shall be construed to establish an employment, partnership, or joint venture relationship between you and RolldUp. This Agreement, and your rights and obligations herein, may not be assigned, subcontracted, delegated, or otherwise transferred by you without RolldUp’s prior written consent, and any attempted assignment, subcontract, delegation, or transfer in violation of the foregoing will be null and void. The terms of this Agreement shall be binding upon assignees.`,
    'RolldUp Contact Information': `For questions about the RolldUp Services we provide, please feel free to contact our Customer Service department at support@rolldupapp.com or call (918) 770-8108 to speak to a representative.`,
    'Additional Terms that may apply to you ': `Commercial Terms: These Additional Terms apply if you also access or use our RolldUp Products or services for any commercial or business purpose, including advertising, maintaining a business listing page, or selling goods or services.`
}