apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: application
resources:
- ../base
patches:
- path: ingress-patch.json
  target:
    kind: Ingress
    name: front-end
patchesStrategicMerge:
- deployment-patch.yaml
- pdb-patch.yaml
