export enum LogFormActionType {
    CHANGE_FOCUS_ELEMENT = 'CHANGE_FOCUS_ELEMENT',
    UPDATE_CATEGORY = 'UPDATE_CATEGORY',
    UPDATE_STRAIN_NAME = 'UPDATE_STRAIN_NAME',
    UPDATE_RATING = 'UPDATE_RATING',
    UPDATE_REVIEW = 'UPDATE_REVIEW',
    UPDATE_STRAIN_INDEX = 'UPDATE_STRAIN_INDEX',
    UPDATE_MGS = 'UPDATE_MGS',
    UPDATE_PERCENTAGE = 'UPDATE_PERCENTAGE',
    UPDATE_CANNIBINOID = 'UPDATE_CANIBINOID',
    UPDATE_PURCHASE_LOCATION = 'UPDATE_PURCHASE_LOCATION',
    UPDATE_BRAND = 'UPDATE_BRAND',
    UPDATE_PRODUCT = 'UPDATE_PRODUCT',
    UPDATE_ERROR_MESSAGE = 'UPDATE_ERROR_MESSAGE',
    RESET_FORM = 'RESET_FORM'
}